server:
  port: 8087 

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     
    show-sql: true

gateway:
  token: gateway-internal-secret-token

internal:
  service:
    token: internal-service-secret-token

# Razorpay configuration (TEST MODE)
razorpay:
  key-id: rzp_test_S4cFKDRXObjqX4
  key-secret: JtUDm8dTu7PjArHFM5phNUAS
  webhook-secret: anvycart-payment-webhook-secret-2026@razorpay

services:
  order-service:
    url: http://localhost:8086/internal/orders