server:
  port: 8086

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gateway:
  token: gateway-internal-secret-token

internal:
  service:
    token: internal-service-secret-token

services:
  user-service:
    url: http://localhost:8082/internal/users

  product-service:
    url: http://localhost:8083/internal/products

  inventory-service:
    url: http://localhost:8084/internal/inventories

  cart-service:
    url: http://localhost:8085/internal/cart

  payment-service:
    url: http://localhost:8087/internal/payments
  
  delivery-service:
    url: http://localhost:8088/internal/deliveries

payment:
  currency-type: INR
