server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:${product.image.upload-dir}

gateway:
  token: gateway-internal-secret-token
  base-url: http://localhost:8080

internal:
  service:
    token: internal-service-secret-token

inventory:
  service:
    base-url: http://localhost:8080/internal/inventories

product:
  image:
    upload-dir: /home/niles/Projects/E-Commerce/images/
